### ISSUE TITLE
✨ Add all maintainers to package.yml output using this workflow [python programming]

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/update-web-metadata#5]
Currently, the workflow in this repo will create an output file [called packages.yml that is a data file](https://github.com/pyOpenSci/pyopensci.github.io/blob/main/_data/packages.yml). 

[This data file drives our websites packages listing here. ](https://www.pyopensci.org/python-packages.html). The data file template for a single package is below. 

This is useful however we need to add a all_maintainers list o that we can list all maintainers of the package not just the submitting author. [Our new template](https://github.com/pyOpenSci/software-submission/blob/main/.github/ISSUE_TEMPLATE/submit-software-for-review.md) does include a `All current maintainers:` so we should be able to parse that section of the issue .

Output packages.yml file currently look ssomething like this (NOTE that i've edited the categories format manually - a separate issue to be opened):

```
- package_name: xclim
  package_description: Climate indices computation package based on Xarray
  submitting_author:
      name: Trevor James Smith
      github_username: Zeitsperre
  repository_link: https://github.com/Ouranosinc/xclim
  version_submitted: v0.40.0
  categories:
    - data-munging
    - reproducibility
    - geospatial
  editor:
      name:
      github_username: Batalex
  reviewer_1:
      name:
      github_username: jmunroe
  reviewer_2:
      name:
      github_username: aguspesce
  archive: TBD
  version_accepted: TBD
  created_at: '2023-01-16T16:59:20Z'
  updated_at: '2023-04-12T20:21:36Z'
  closed_at:
  gh_meta:
      name: xclim
      description: 'Library of derived climate variables, ie climate indicators,
          based on xarray. '
      created_at: 07/27/2018
      stargazers_count: 225
      watchers_count: 225
      forks: 43
      open_issues_count: 49
      forks_count: 43
      documentation: https://xclim.readthedocs.io/en/stable/
      contrib_count: 26
      last_commit: 04/12/2023
```

We should add code that creates a section like this to the yaml file (maintainers list):
```
- package_name: xclim
  package_description: Climate indices computation package based on Xarray
  submitting_author:
    - name: Trevor James Smith
      github_username: Zeitsperre
  maintainers:
    - name:
      github_username: user_name_here
```
related TODO: leah should update all old issues to have all-maintainers!
