### ISSUE TITLE
bug in package meta output - fork values appear twice!

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/update-web-metadata#50]
@SultanOrazbayev noticed [here](https://github.com/pyOpenSci/pyopensci.github.io/pull/254)  that in our automated workflow - [forks are listed twice](https://github.com/pyOpenSci/pyopensci.github.io/pull/253/files#diff-2511ccad422b02cde04c39c34bf5e5c87952a50fe83f53ff56f8fa7ce43de6ffR34) . 
```
 gh_meta:
      name: bibat
      description: A batteries-included template for Bayesian data analysis projects
      created_at: 03-04-2021
      stargazers_count: 10
      watchers_count: 10
      forks: 2
      open_issues_count: 8
      forks_count: 2
      documentation: https://bibat.readthedocs.io/
      contrib_count: 1
      last_commit: 07-14-2023
```

fix the metadata part of the workflow to remove that duplication! the metadata is captured in the parse_issues.py module.
