### ISSUE TITLE
✨ Update package categories format in pyosmet update workflow to produce a better packages.yml file [Python programming]

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/update-web-metadata#6]
Currently, the workflow in this repo will create an output file [called packages.yml that is a data file](https://github.com/pyOpenSci/pyopensci.github.io/blob/main/_data/packages.yml). 

[This data file drives our websites packages listing here. ](https://www.pyopensci.org/python-packages.html). The data file template for a single package is below. 

Output packages.yml file currently looks something like this (NOTE that i've edited the categories format manually - a separate issue to be opened):

Note in the yaml file below the categories often have two works with a space in between `Data munging` and sometimes there are capital letters. However for the website we need the categories to be lower case and using dashes rather than spaces. `data-munging`. I've been updating this manually but we should just update the code to fix the category style returned in the packages.yml file. 

```
- package_name: xclim
  package_description: Climate indices computation package based on Xarray
  submitting_author:
      name: Trevor James Smith
      github_username: Zeitsperre
  repository_link: https://github.com/Ouranosinc/xclim
  version_submitted: v0.40.0
  categories:
    - Data munging
    - Reproducibility
    - Geospatial
```
